"""Add model Direction_translation

Revision ID: c6a30a38aff7
Revises: 56acd1162dd5
Create Date: 2024-10-04 23:02:23.780326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6a30a38aff7'
down_revision: Union[str, None] = '56acd1162dd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direction_translations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('language_input_id', sa.Integer(), nullable=False),
    sa.Column('language_output_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['language_input_id'], ['languages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['language_output_id'], ['languages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('direction_translations')
    # ### end Alembic commands ###
